name = "Poingr"
uuid = "573615e8-489b-4e48-952b-fc194aa7573b"
authors = ["Keita Nakamura <keita.nakamura.1109@gmail.com>"]
version = "0.20.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tensorial = "98f94333-fa9f-48a9-ad80-1c66397b2b38"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
ProgressMeter = "1.5"
Reexport = "1"
StaticArrays = "1"
StructArrays = "0.6"
Tensorial = "0.11"
WriteVTK = "1.9"
julia = "1.6"
